### ISSUE TITLE
paper1.12.2使用最新版插件在玩家登入服务器时会报错

### ISSUE THREAD

**Issue by 3318311689** [Skillw/AttributeSystem#1]
[10:04:30 ERROR]: Could not pass event PlayerJoinEvent to AttributeSystem v1.4.4-SNAPSHOT-30
java.lang.NullPointerException: null
        at com.skillw.attsystem.internal.manager.EquipmentDataManagerImpl.update(EquipmentDataManagerImpl.kt:45) ~[?:?]
        at com.skillw.attsystem.internal.manager.AttributeSystemAPIImpl.update(AttributeSystemAPIImpl.kt:158) ~[?:?]
        at com.skillw.attsystem.api.AttrAPI.updateAttr(AttrAPI.kt:40) ~[?:?]
        at com.skillw.attsystem.internal.feature.listener.update.EntityUpdate.onPlayerRespawn(EntityUpdate.kt:22) ~[?:?]
        at java.lang.invoke.MethodHandle.invokeWithArguments(MethodHandle.java:627) ~[?:1.8.0_201]
        at com.skillw.attributesystem.taboolib.library.reflex.JavaClassMethod.invoke(JavaClassMethod.kt:31) ~[?:?]
        at com.skillw.attributesystem.taboolib.common.platform.event.EventBus.invoke(EventBus.kt:132) ~[?:?]
        at com.skillw.attributesystem.taboolib.common.platform.event.EventBus.invoke$default(EventBus.kt:130) ~[?:?]
        at com.skillw.attributesystem.taboolib.common.platform.event.EventBus$registerBukkit$2.invoke(EventBus.kt:77) ~[?:?]
        at com.skillw.attributesystem.taboolib.common.platform.event.EventBus$registerBukkit$2.invoke(EventBus.kt:76) ~[?:?]
        at com.skillw.attributesystem.taboolib.common.platform.function.ListenerKt$registerBukkitListener$1.invoke(Listener.kt:36) ~[?:?]
        at com.skillw.attributesystem.taboolib.common.platform.function.ListenerKt$registerBukkitListener$1.invoke(Listener.kt:36) ~[?:?]
        at com.skillw.attributesystem.taboolib.platform.BukkitListener$registerListener$listener$1.invoke(BukkitListener.kt:35) ~[?:?]
        at com.skillw.attributesystem.taboolib.platform.BukkitListener$registerListener$listener$1.invoke(BukkitListener.kt:35) ~[?:?]
        at com.skillw.attributesystem.taboolib.platform.BukkitListener$BukkitListener.execute(BukkitListener.kt:72) ~[?:?]
        at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:78) ~[patched_1.12.2.jar:git-Paper-1620]
        at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62) ~[patched_1.12.2.jar:git-Paper-1620]
        at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:513) ~[patched_1.12.2.jar:git-Paper-1620]
        at net.minecraft.server.v1_12_R1.PlayerList.onPlayerJoin(PlayerList.java:370) ~[patched_1.12.2.jar:git-Paper-1620]
        at net.minecraft.server.v1_12_R1.PlayerList.a(PlayerList.java:183) ~[patched_1.12.2.jar:git-Paper-1620]
        at net.minecraft.server.v1_12_R1.LoginListener.b(LoginListener.java:178) ~[patched_1.12.2.jar:git-Paper-1620]
        at net.minecraft.server.v1_12_R1.LoginListener.e(LoginListener.java:68) ~[patched_1.12.2.jar:git-Paper-1620]
        at net.minecraft.server.v1_12_R1.NetworkManager.a(NetworkManager.java:273) ~[patched_1.12.2.jar:git-Paper-1620]
        at net.minecraft.server.v1_12_R1.ServerConnection.c(ServerConnection.java:150) ~[patched_1.12.2.jar:git-Paper-1620]
        at net.minecraft.server.v1_12_R1.MinecraftServer.D(MinecraftServer.java:948) ~[patched_1.12.2.jar:git-Paper-1620]
        at net.minecraft.server.v1_12_R1.DedicatedServer.D(DedicatedServer.java:423) ~[patched_1.12.2.jar:git-Paper-1620]
        at net.minecraft.server.v1_12_R1.MinecraftServer.C(MinecraftServer.java:774) ~[patched_1.12.2.jar:git-Paper-1620]
        at net.minecraft.server.v1_12_R1.MinecraftServer.run(MinecraftServer.java:666) ~[patched_1.12.2.jar:git-Paper-1620]
        at java.lang.Thread.run(Thread.java:748) [?:1.8.0_201]
[10:04:30 ERROR]: Could not pass event PlayerJoinEvent to AttributeSystem v1.4.4-SNAPSHOT-30
java.lang.NullPointerException: null
        at com.skillw.attsystem.internal.manager.EquipmentDataManagerImpl.update(EquipmentDataManagerImpl.kt:45) ~[?:?]
        at com.skillw.attsystem.internal.manager.AttributeSystemAPIImpl.update(AttributeSystemAPIImpl.kt:158) ~[?:?]
        at com.skillw.attsystem.internal.feature.listener.person.Personal.init(Personal.kt:20) ~[?:?]
        at com.skillw.attsystem.internal.feature.listener.person.Personal.onPlayerJoin(Personal.kt:34) ~[?:?]
        at java.lang.invoke.MethodHandle.invokeWithArguments(MethodHandle.java:627) ~[?:1.8.0_201]
        at com.skillw.attributesystem.taboolib.library.reflex.JavaClassMethod.invoke(JavaClassMethod.kt:31) ~[?:?]
        at com.skillw.attributesystem.taboolib.common.platform.event.EventBus.invoke(EventBus.kt:132) ~[?:?]
        at com.skillw.attributesystem.taboolib.common.platform.event.EventBus.invoke$default(EventBus.kt:130) ~[?:?]
        at com.skillw.attributesystem.taboolib.common.platform.event.EventBus$registerBukkit$2.invoke(EventBus.kt:77) ~[?:?]
        at com.skillw.attributesystem.taboolib.common.platform.event.EventBus$registerBukkit$2.invoke(EventBus.kt:76) ~[?:?]
        at com.skillw.attributesystem.taboolib.common.platform.function.ListenerKt$registerBukkitListener$1.invoke(Listener.kt:36) ~[?:?]
        at com.skillw.attributesystem.taboolib.common.platform.function.ListenerKt$registerBukkitListener$1.invoke(Listener.kt:36) ~[?:?]
        at com.skillw.attributesystem.taboolib.platform.BukkitListener$registerListener$listener$1.invoke(BukkitListener.kt:35) ~[?:?]
        at com.skillw.attributesystem.taboolib.platform.BukkitListener$registerListener$listener$1.invoke(BukkitListener.kt:35) ~[?:?]
        at com.skillw.attributesystem.taboolib.platform.BukkitListener$BukkitListener.execute(BukkitListener.kt:72) ~[?:?]
        at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:78) ~[patched_1.12.2.jar:git-Paper-1620]
        at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62) ~[patched_1.12.2.jar:git-Paper-1620]
        at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:513) ~[patched_1.12.2.jar:git-Paper-1620]
        at net.minecraft.server.v1_12_R1.PlayerList.onPlayerJoin(PlayerList.java:370) ~[patched_1.12.2.jar:git-Paper-1620]
        at net.minecraft.server.v1_12_R1.PlayerList.a(PlayerList.java:183) ~[patched_1.12.2.jar:git-Paper-1620]
        at net.minecraft.server.v1_12_R1.LoginListener.b(LoginListener.java:178) ~[patched_1.12.2.jar:git-Paper-1620]
        at net.minecraft.server.v1_12_R1.LoginListener.e(LoginListener.java:68) ~[patched_1.12.2.jar:git-Paper-1620]
        at net.minecraft.server.v1_12_R1.NetworkManager.a(NetworkManager.java:273) ~[patched_1.12.2.jar:git-Paper-1620]
        at net.minecraft.server.v1_12_R1.ServerConnection.c(ServerConnection.java:150) ~[patched_1.12.2.jar:git-Paper-1620]
        at net.minecraft.server.v1_12_R1.MinecraftServer.D(MinecraftServer.java:948) ~[patched_1.12.2.jar:git-Paper-1620]
        at net.minecraft.server.v1_12_R1.DedicatedServer.D(DedicatedServer.java:423) ~[patched_1.12.2.jar:git-Paper-1620]
        at net.minecraft.server.v1_12_R1.MinecraftServer.C(MinecraftServer.java:774) ~[patched_1.12.2.jar:git-Paper-1620]
        at net.minecraft.server.v1_12_R1.MinecraftServer.run(MinecraftServer.java:666) ~[patched_1.12.2.jar:git-Paper-1620]
        at java.lang.Thread.run(Thread.java:748) [?:1.8.0_201]

**Comment by Glomzzz** [comment]
已修复
