### ISSUE TITLE
数据库问题

### ISSUE THREAD

**Issue by Blum3nkranz** [Skillw/AttributeSystem#14]
使用mysql，buffsystem以及attributesystem生成的表中，各个字段的默认长度为0，导致插件塞不进去数据
手动更改字段长度可以解决
paper-1.20.1-196

[22:41:12] [Craft Scheduler Thread - 23 - Pouvoir/WARN]: [Pouvoir] Query: INSERT INTO `buff_data` (`username`, `key`, `value`) VALUES (?, ?, ?)
[22:41:12] [Craft Scheduler Thread - 23 - Pouvoir/WARN]: [Pouvoir] Parameters (3): [BouncyArrow, buff-data, null]
[22:41:12] [Craft Scheduler Thread - 23 - Pouvoir/WARN]: [Pouvoir] Plugin Pouvoir v1.6.7-beta-6 generated an exception while executing task 2517
com.mysql.cj.jdbc.exceptions.MysqlDataTruncation: Data truncation: Data too long for column 'username' at row 1
	at com.mysql.cj.jdbc.exceptions.SQLExceptionsMapping.translateException(SQLExceptionsMapping.java:104) ~[mysql-connector-j-8.0.33.jar:8.0.33]
	at com.mysql.cj.jdbc.ServerPreparedStatement.serverExecute(ServerPreparedStatement.java:555) ~[mysql-connector-j-8.0.33.jar:8.0.33]
	at com.mysql.cj.jdbc.ServerPreparedStatement.executeInternal(ServerPreparedStatement.java:339) ~[mysql-connector-j-8.0.33.jar:8.0.33]
	at com.mysql.cj.jdbc.ClientPreparedStatement.executeUpdateInternal(ClientPreparedStatement.java:1061) ~[mysql-connector-j-8.0.33.jar:8.0.33]
	at com.mysql.cj.jdbc.ClientPreparedStatement.executeUpdateInternal(ClientPreparedStatement.java:1009) ~[mysql-connector-j-8.0.33.jar:8.0.33]
	at com.mysql.cj.jdbc.ClientPreparedStatement.executeLargeUpdate(ClientPreparedStatement.java:1320) ~[mysql-connector-j-8.0.33.jar:8.0.33]
	at com.mysql.cj.jdbc.ClientPreparedStatement.executeUpdate(ClientPreparedStatement.java:994) ~[mysql-connector-j-8.0.33.jar:8.0.33]
	at com.zaxxer.hikari_4_0_3.pool.ProxyPreparedStatement.executeUpdate(ProxyPreparedStatement.java:61) ~[Pouvoir-1.6.7-beta-6.jar:?]
	at com.zaxxer.hikari_4_0_3.pool.HikariProxyPreparedStatement.executeUpdate(HikariProxyPreparedStatement.java) ~[Pouvoir-1.6.7-beta-6.jar:?]
	at com.skillw.pouvoir.taboolib.module.database.ExecutableSource$executeUpdate$1$1.invoke(ExecutableSource.kt:100) ~[Pouvoir-1.6.7-beta-6.jar:?]
	at com.skillw.pouvoir.taboolib.module.database.ExecutableSource$executeUpdate$1$1.invoke(ExecutableSource.kt:98) ~[Pouvoir-1.6.7-beta-6.jar:?]
	at com.skillw.pouvoir.taboolib.module.database.UtilKt.use(Util.kt:40) ~[Pouvoir-1.6.7-beta-6.jar:?]
	at com.skillw.pouvoir.taboolib.module.database.ExecutableSource.executeUpdate$lambda$3(ExecutableSource.kt:98) ~[Pouvoir-1.6.7-beta-6.jar:?]
	at com.skillw.pouvoir.taboolib.module.database.ResultProcessor$Update.run(ResultProcessor.kt:18) ~[Pouvoir-1.6.7-beta-6.jar:?]
	at com.skillw.pouvoir.taboolib.module.database.ResultProcessorList.run(ResultProcessorList.kt:33) ~[Pouvoir-1.6.7-beta-6.jar:?]
	at com.skillw.pouvoir.internal.feature.database.sql.SQLTable.insert(SQLTable.kt:44) ~[Pouvoir-1.6.7-beta-6.jar:?]
	at com.skillw.pouvoir.internal.feature.database.sql.NormalContainer.insert(NormalContainer.kt) ~[Pouvoir-1.6.7-beta-6.jar:?]
	at com.skillw.pouvoir.internal.feature.database.sql.UserDatabase.insert(UserDatabase.kt) ~[Pouvoir-1.6.7-beta-6.jar:?]
	at com.skillw.pouvoir.internal.feature.database.sql.UserDatabase.set(UserDatabase.kt:55) ~[Pouvoir-1.6.7-beta-6.jar:?]
	at com.skillw.pouvoir.internal.feature.database.sql.UserDatabase.saveAll(UserDatabase.kt:19) ~[Pouvoir-1.6.7-beta-6.jar:?]
	at com.skillw.pouvoir.internal.feature.database.sql.UserContainer$onEnable$1.invoke(UserContainer.kt:33) ~[Pouvoir-1.6.7-beta-6.jar:?]
	at com.skillw.pouvoir.internal.feature.database.sql.UserContainer$onEnable$1.invoke(UserContainer.kt:32) ~[Pouvoir-1.6.7-beta-6.jar:?]
	at com.skillw.pouvoir.taboolib.platform.BukkitExecutor$BukkitRunningTask$instance$1.run(BukkitExecutor.kt:87) ~[Pouvoir-1.6.7-beta-6.jar:?]
	at org.bukkit.craftbukkit.v1_20_R1.scheduler.CraftTask.run(CraftTask.java:101) ~[paper-1.20.1.jar:git-Paper-196]
	at org.bukkit.craftbukkit.v1_20_R1.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:57) ~[paper-1.20.1.jar:git-Paper-196]
	at com.destroystokyo.paper.ServerSchedulerReportingWrapper.run(ServerSchedulerReportingWrapper.java:22) ~[paper-1.20.1.jar:?]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144) ~[?:?]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642) ~[?:?]
	at java.lang.Thread.run(Thread.java:1583) ~[?:?]

**Comment by Blum3nkranz** [comment]
pouvir一样
![image](https://github.com/user-attachments/assets/3de32228-7e28-4ecb-9839-bb70cd99d262)

**Comment by Glomzzz** [comment]
好 感谢提出issue，我会尽快修复

**Comment by xinge54088** [comment]
修复是你的谎言 ：(
